### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Marmelatze** [szymach/c-pchart#19]
Hi,

what is the license of this library? The compose file state MIT, but some classes contain a reference to http://www.pchart.net/license

**Comment by szymach** [comment]
Well I don't *own* the pChart library, this is only a wrapper. So my code is MIT, since I can't make any claims to the pChart library, but if you want to use it in a commercial product, you still need to pay the author. I think I may have to disclose that in the readme.

**Comment by szymach** [comment]
Or I'll have to change it to GNU, to be honest. That's what the author says :P Thanks for pointing that out.

**Comment by szymach** [comment]
I assume this is safe to close :)
