### ISSUE TITLE
Exceptions not namespaced

### ISSUE THREAD

**Issue by magnusjt** [szymach/c-pchart#20]
In various places I see "throw new Exception". This doesn't work within namespaces. Should be "throw new \Exception" (with the backslash added).

**Comment by szymach** [comment]
Well I do import them via `use Exception;` statement on the top of the class. Is there a place where I forgot to do it?

**Comment by magnusjt** [comment]
Ah yes, I see you've added it in some files. It is missing in BaseDraw.php at least.

**Comment by szymach** [comment]
You're right, would you be so kind as to create a PR that will add missing uses?
