### ISSUE TITLE
Is the dependency on PHP 5.5 really necessary?

### ISSUE THREAD

**Issue by ywarnier** [szymach/c-pchart#27]
In composer.json, you have updated the dependency some time ago from PHP 5.3 directly to PHP 5.5. 
Could that dependency be brought back to PHP 5.4?

We use your lib in Chamilo (a large e-learning platform) and we plan on maintaining the current version with support for PHP 5.4. However, we also want to support 7.0 and 7.1. Supporting PHP 7 implies using version 2 of c-pchart, but this one depends on PHP 5.5, which would force us to choose between supporting 5.4 and supporting 7.0.

Can you see the difficult choice we face?

I haven't checked the c-pchart 2 in PHP 5.4 yet, to check if it works, but thought that maybe you would still remember what forced you to move to 5.5 or if it was just a decision without a specific reason behind it...

**Comment by szymach** [comment]
The reason for bumping up the requirement, if I recall correctly, was one of the Behat's dependencies (I think it was one of `guzzle` libraries). I will check and get back at you soon.

Anyway, why bother with 5.4? It is no longer supported (5.5 as well, for that matter), slow, and increases costs of maintaining backwards compatibility in your platform. I do not presume to tell you how to run your stuff, but perhaps dropping support for versions earlier than 7 (5.6 max) would be a good thing? Let me know what you think :)

**Comment by szymach** [comment]
Right, I checked and it was as I suspected. This project was my first real adventure with creating open source packages and I simply misunderstood some things. If I recall correctly, basically I had installed dependencies for PHP 5.6 (`ignore-platform-reqs` :P ) and later tried to use the same set of packages on 5.4, which of course resulted in failures. Hence the update of requirements. I guess I can lower it back to 5.4, although to be honest I will be doing this with a very sad face.

**Comment by ywarnier** [comment]
We will drop support for PHP 5.* altogether when publishing Chamilo version 2.0 by the end of the year (hopefully). However, we still have a lot of users (open source) using PHP 5.4 with our current version 1.11.2. We launched 1.11.0 when PHP 5.4 was in its end of life, and it already generated a good (constructive) discussion. Our association's goal is to increase the availability of quality education around the world, and this (sadly) often relies on old-ish infrastructures, with PHP 5.4 or lower (like in the case of the One Laptop Per Child project's XO laptops). Moving unnecessarily our dependencies would be selfish and probably affect thousands of portals. Version 2.0 of Chamilo brings a series of projects that require a minimum of PHP 5.6, and we believe that by the time we finish it, a series of other libraries will depend strictly on PHP >=7.0, so we've got a clear view of what we want.

Now we don't like to fork and re-do things if we can re-use them (because that slows us down to develop more features for teachers and students in developing countries), but there's a balance between that and moving to a requirement that will require thousands of *teachers* (yeah, our portals installers are not usually engineers) to upgrade their infrastructure, many times meaning also upgrading their operating systems and loosing support for other stuff they use.

How easy would things be if we had no users :-D

So yes, I would really appreciate it if you could lower the requirement to PHP 5.4, but now you know the story, you can take a better decision. I'm not forcing you, but it's likely we'd do a small (temporary) fork if that doesn't work for you (it sounds threatening but it isn't, it's just that we have to find a solution).

Oh, and yes, we *love* PHP 7!
