### ISSUE TITLE
Licensing conundrum

### ISSUE THREAD

**Issue by bowlofeggs** [szymach/c-pchart#35]
Hello!

I have been working on packaging this library for Fedora, but we came across a licensing conundrum: due to the wording in pChart's license about making money and commercial use, there is a logical contradiction in the licensing:

If person A is non-commercial and uses pChart under the GPL, can they then give pChart to comany B who will make money under it? The GPL says "of course", but the pChart license excludes this possibility.

I attempted to contact the pChart authors a week ago to ask them to alter the wording on their [license page](http://www.pchart.net/license), but I have not heard back from them. If you know how to get in touch with them, I encourage you to do so.

Here is the message I sent them last week:

```
Hello!

I work on the Fedora Project[0] and I am interested in packaging pchart
for Fedora. There is some confusing language on the pchart licensing
page[1] around whether the GPL license is truly GPL or not, as it has a
statement about whether money is made or not. The GPL does not prevent
making money with the software, it just has rules about what can and
can't be done with the software that isn't particularly friendly
towards closed source use.

Unfortunately, the use of the word commercial and the "you make money
by distributing it" statement means that pchart isn't truly GPL, as the
GPL does not restrict profit and in fact it is not compatible with the
idea of restricting profits. I brought this issue up on Fedora's legal
mailing list, and it was ruled that pchart cannot be distributed with
Fedora due to the statement[2]. One of the replies on the thread was
from Richard Fontana[3], a notable authority on GPL licensing.

This statement causes a paradox as well - suppose that person A accepts
pchart under the GPL (and person A does not make money with it).
Suppose then that person A gives pchart to company B under the terms of
the GPL (which they have the right to do with the GPL they were given)
and then company B makes money off of it, while abiding by the GPL. Is
company B violating the license? The wording on the license page makes
this situation unclear. 

However, after reading some forum posts about the license[4] I came to
believe that perhaps the license page was intended to communicate that
the library is publicly licensed GPL for any use allowed by the GPL
(including making money as a commercial entity), but that pchart was
available under other licenses for a fee if someone wanted to
distribute pchart with or as closed source software. There are other
examples of this style of dual licensing, but they typically don't use
wording about commercial use or making money. Is this the intention of
the license? If so, would you be willing to adjust the wording on that
page? Without an adjustment, this library won't be allowed to be part
of the Fedora project.


[0] https://getfedora.org/
[1] http://www.pchart.net/license
[2] https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/4MDAWLRSVR3QIIYFJLVKMEELS5OPBIMI/
[3] https://en.wikipedia.org/wiki/Richard_Fontana
[4] http://wiki.pchart.net/forum/viewtopic.php?f=3&t=2163&p=3784&hilit=license#p3784
```

**Comment by szymach** [comment]
Hello,
The MIT license is incorrect, yes, and I changed it in `composer.json` a while ago. Seems I forgot to remove the text file and did not notice that GitHub uses it to discern the license type. As for contacting the author, I have never attempted it and doubt I would have any more luck than you do. By the way, as far as I can recall he does have a LinkedIn profile, so maybe try reaching him there?

**Comment by bowlofeggs** [comment]
I did attempt to contact upstream via Linked In last week as per your suggestion, but have not heard back yet. Thanks for the suggestion!

**Comment by szymach** [comment]
Hey, I do not think this issue is going to be resolved anytime soon (or ever, to be honest, considering the lack of feedback). If it is OK with you, I will just close this and if anything changes, you can just open a new one.

**Comment by bowlofeggs** [comment]
On Fri, 2017-06-23 at 13:17 -0700, Piotr Szymaszek wrote:
> Hey, I do not think this issue is going to be resolved anytime soon
> (or ever, to be honest, considering the lack of feedback). If it is
> OK with you, I will just close this and if anything changes, you can
> just open a new one.

I was able to get a response from the upstream author on Linked In, but
only once and I didn't get a response to my follow up response
unfortunately.

I'm happy if you want to close this for now. If I am able to persuade
upstream to change their position I can send you a PR (with supporting
evidence that it has changed, of course ☺).

Thanks for your help!

**Comment by szymach** [comment]
Alright, closing then. Good luck with using them persuasion skills :)
