### ISSUE TITLE
PHP 7.1: Uncaught Error: [] operator not supported for strings in (...)/vendor/szymach/c-pchart/src/BaseDraw.php on line 784

### ISSUE THREAD

**Issue by caugner** [szymach/c-pchart#44]
I'm getting the above mentioned fatal error with CpChart 3.0.0 and PHP 7.1.6.

The reason is that `BaseDraw` initialises a variable `$Width = ""`, but uses it like an `array`:
https://github.com/szymach/c-pchart/blob/08a2937e0b1f73f1105aa6fbd3f8873a1e43ed52/src/BaseDraw.php#L763-L784

**Comment by caugner** [comment]
As far as I can see, the solution should be to

* replace `$Width = "";`  by `$Width = [];` and
* add an `unset($Width);` after `$Width[] = $BoxArray[1]["X"];`.

**Comment by szymach** [comment]
Man, I thought I found all of these. Thanks for pointing this out.
