### ISSUE TITLE
Pie charts not rendering with PHP 7.1

### ISSUE THREAD

**Issue by ehymel** [szymach/c-pchart#46]
After upgrading to PHP 7.1, pie charts are not fully rendered. Labels are in place, but the actual plots are missing from generated images.

**Comment by szymach** [comment]
Hello, please support some code for me to test.

**Comment by szymach** [comment]
Also, which version are you using?

**Comment by szymach** [comment]
Another also - please try [these](https://github.com/szymach/c-pchart/blob/master/tests/unit/PieTest.php) examples and tell me if the output is correct. Should yield the following images:
![draw2dpie](https://user-images.githubusercontent.com/2230556/28250970-40094900-6a74-11e7-988d-dc1b2a43c3d1.png)
![draw2dring](https://user-images.githubusercontent.com/2230556/28250972-400cb892-6a74-11e7-989e-a8ef1d13c265.png)
![draw3dpie](https://user-images.githubusercontent.com/2230556/28250971-400c6310-6a74-11e7-9c79-9b47e40a2e22.png)
![draw3dring](https://user-images.githubusercontent.com/2230556/28250973-400d1c1a-6a74-11e7-957f-e71e734c2aea.png)

**Comment by ehymel** [comment]
ok, your test code does work. I am using PHP 7.1.6 and c-pchart 2.0.9. 
The code that does not work is from your example [here](https://github.com/szymach/c-pchart/blob/master/resources/doc/2d_pie.md).

**Comment by ehymel** [comment]
OK, I found the change.
In the new test files you linked above, you define and then add data like so:

$data = new Data();
$data->addPoints([40, 60, 15, 10, 6, 4], "ScoreA");

whereas previously you could pass data through the constructor:
$data = new Data([40, 60, 15, 10, 6, 4], "ScoreA");

That seems to have changed, so no data is getting to images. Making this change in my scripts fixes the problem completely.

btw, thanks for your work on this. Saved me tons of time!

**Comment by szymach** [comment]
Passing arguments through the constructor and `addPoints` should work the same >.>

Anyways, I will check what is the problem. Thank you for your submission :)

**Comment by szymach** [comment]
OK I have fixed the documentation and tests regarding the passing of data to the constructor. I will make a release after I will resolve the issues with the palettes.
