### ISSUE TITLE
Wrong array key referenced

### ISSUE THREAD

**Issue by spiro79** [szymach/c-pchart#49]
The line shows:
`$DisplayFont = isset($Format["DisplaySize"]) ? $Format["DisplaySize"] : $this->FontName;`
But it should be:
`$DisplayFont = isset($Format["DisplayFont"]) ? $Format["DisplayFont"] : $this->FontName;`

https://github.com/szymach/c-pchart/blob/3e04e49c00b48d388a9db7963f28a54b5c03f7d5/src/Draw.php#L7259

**Comment by szymach** [comment]
Fixed in both active branches
