### ISSUE TITLE
packagist 

### ISSUE THREAD

**Issue by devpingu** [szymach/c-pchart#61]
I don’t know if you've seen, on packagist to install with composer, the command is “composer create-project” instead “composer require”

Kind regards 

![pchart](https://user-images.githubusercontent.com/36487581/54828818-47dd7c80-4cb5-11e9-8946-77747f63c110.png)

**Comment by szymach** [comment]
Indeed. the `type` field value provided in the `composer.json` was `project` instead of `library`, corrected now. Thanks for the info :)
