### ISSUE TITLE
PHP8.1: imagefilledpolygon(): Using the $num_points parameter is deprecated

### ISSUE THREAD

**Issue by Findus23** [szymach/c-pchart#68]
Just an early heads-up:
Using the PHP8.1 beta2 the following deprecation warning is shown:
> Deprecated - imagefilledpolygon(): Using the $num_points parameter is deprecated

https://github.com/szymach/c-pchart/blob/c71e1d8f08037148e684dd7b7bf22a3d2eeefe06/src/Draw.php#L81-L83

see also https://www.php.net/manual/en/function.imagefilledpolygon.php

**Comment by szymach** [comment]
Solved by #74
