### ISSUE TITLE
PHP8.1: Implicit conversion from float to int loses precision

### ISSUE THREAD

**Issue by Findus23** [szymach/c-pchart#69]
Another early heads-up:

> Deprecated - Implicit conversion from float 74.08333333332371 to int loses precision

https://github.com/szymach/c-pchart/blob/c71e1d8f08037148e684dd7b7bf22a3d2eeefe06/src/BaseDraw.php#L288
https://github.com/szymach/c-pchart/blob/c71e1d8f08037148e684dd7b7bf22a3d2eeefe06/src/BaseDraw.php#L510
https://github.com/szymach/c-pchart/blob/c71e1d8f08037148e684dd7b7bf22a3d2eeefe06/src/Draw.php#L1312
see https://wiki.php.net/rfc/implicit-float-int-deprecate

**Comment by szymach** [comment]
Solved by #74
