### ISSUE TITLE
Unsupport full php 8.1

### ISSUE THREAD

**Issue by Mon1k** [szymach/c-pchart#76]
my code:

`
require "vendor/autoload.php";

use CpChart\Chart\Radar;
use CpChart\Data;
use CpChart\Image;

error_reporting(E_ALL | E_STRICT);
ini_set("log_errors", "on");
ini_set("display_errors", "on");

$values = [
    9,
    9.29,
    10,
    10,
    8.5
];

$width  = 400;
$height = 400;

$data = new Data;
$data->addPoints($values, "Score");
$data->setSerieDescription("Score", "222");

$data->addPoints(["111", "222", "333", "444", "555"], "Labels");
$data->setAbscissa("Labels");
$data->setPalette("Score", ["R" => 157, "G" => 96, "B" => 22]);

$image = new Image($width, $height, $data);
$image->setFontProperties(["FontName" => 'resource/fonts/SourceSansPro-Regular.ttf', "FontSize" => 10, "R" => 80, "G" => 80, "B" => 80]);

$image->setShadow(true, ["X" => 2, "Y" => 2, "R" => 0, "G" => 0, "B" => 0, "Alpha" => 10]);

$radar = new Radar;
$image->setGraphArea(0, 0, $width, $height);
$options = ["DrawPoly" => true, "WriteValues" => true, "ValueFontSize" => 7, "Layout" => RADAR_LAYOUT_CIRCLE, "BackgroundGradient" => ["StartR" => 255, "StartG" => 255, "StartB" => 255, "StartAlpha" => 100, "EndR" => 207, "EndG" => 227, "EndB" => 125, "EndAlpha" => 50]];
$radar->drawRadar($image, $data, $options);
`

php:
`
php -v
PHP 8.1.0 (cli) (built: Nov 25 2021 20:22:03) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologie
`

errors:
`
Deprecated: Implicit conversion from float 216.6 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/BaseDraw.php on line 288

Deprecated: Implicit conversion from float 232.6 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/BaseDraw.php on line 288

Deprecated: Implicit conversion from float 52.80000000000001 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1145

Deprecated: Implicit conversion from float 52.80000000000001 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1146

Deprecated: Implicit conversion from float 216.6 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/BaseDraw.php on line 288
`

install v3.0.11:
`
 "name": "szymach/c-pchart",
            "version": "v3.0.11",
            "source": {
                "type": "git",
                "url": "https://github.com/szymach/c-pchart.git",
                "reference": "7022fa093ca142bbe9705504420d30073a5ddf13"
            },
```

**Comment by szymach** [comment]
Hello,
Thank you for the information, I have created a new version restricting the package to PHP 8.0.* until Travis supports 8.1 and the test suite can be ran with it.

**Comment by Mon1k** [comment]
https://travis-ci.community/t/php-8-1-support/12439 - php 8.1 in travis also support

**Comment by szymach** [comment]
Hello,
In version 3.0.13 I have restored the PHP 8.1 support. I have also created a [regression test](https://github.com/szymach/c-pchart/blob/3.0/tests/unit/RegressionTest.php) for the code that you provided and I do not receive any depreciation errors (they would have been visible [here](https://app.travis-ci.com/github/szymach/c-pchart/jobs/572469736#L742). Are you sure this is the source of the issue?

**Comment by Mon1k** [comment]
I run manually:

`Deprecated: Implicit conversion from float 45.14087303500966 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312
PHP Deprecated:  Implicit conversion from float 93.84751357818496 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312

Deprecated: Implicit conversion from float 93.84751357818496 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312
PHP Deprecated:  Implicit conversion from float 243.83025792024176 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1300

Deprecated: Implicit conversion from float 243.83025792024176 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1300
PHP Deprecated:  Implicit conversion from float 55.25476085143799 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1300

Deprecated: Implicit conversion from float 55.25476085143799 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1300
PHP Deprecated:  Implicit conversion from float 241.83025792024176 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312

Deprecated: Implicit conversion from float 241.83025792024176 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312
PHP Deprecated:  Implicit conversion from float 53.25476085143799 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312

Deprecated: Implicit conversion from float 53.25476085143799 to int loses precision in /var/www/test/vendor/szymach/c-pchart/src/Draw.php on line 1312
root@monastery:/var/www/test# /usr/bin/php8.1 -v
PHP 8.1.1 (cli) (built: Dec 31 2021 07:26:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
root@monastery:/var/www/test# /usr/bin/php8.1 ./1.php 
`

also, if remove
`
error_reporting(E_ALL | E_STRICT);
`

then there will be no errors.

**Comment by szymach** [comment]
Alright, I guess I will just have to add manual conversion from float. Thank you.

**Comment by szymach** [comment]
@Mon1k hello, please try version 3.0.14 and let me know if you find any more errors.

**Comment by Mon1k** [comment]
for version 3.0.14 in php 8.1 without errors, thanks.

**Comment by szymach** [comment]
Thank you for submitting the issue

**Comment by szymach** [comment]
`3.1.0` was a mistake, please do not rely on it, since I will be removing it.

**Comment by ehymel** [comment]
ok thanks!
