### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by ehymel** [szymach/c-pchart#79]
I know there is an open issue around PHP 8.1 as well as a pull request about the same, but I'm hoping you'll reconsider support for PHP8.1, especially since symfony 6.1 will [require PHP 8.1](https://symfony.com/blog/symfony-6-1-will-require-php-8-1). I would love to be able to continue using your libraries going forward. Thanks very much.

**Comment by szymach** [comment]
PHP 8.1 is now supported in version 3.1, please use it and report if any issues occur.
