### ISSUE TITLE
utf8_encode is deprecated in PHP 8.2

### ISSUE THREAD

**Issue by Findus23** [szymach/c-pchart#86]
> PHP Deprecated: Function utf8_encode() is deprecated in .../vendor/szymach/c-pchart/constants.php on line 48

https://github.com/szymach/c-pchart/blob/373786c8a9e7651c445b9ce42320b5a66e777dbf/constants.php#L48

If I understand it correctly `utf8_encode("&#8364;")` is the same as `"&#8364;"` (see https://3v4l.org/dERVv), so I think the `utf8_encode()` can simply be removed.

**Comment by szymach** [comment]
I suppose it is a leftover from when this library files were encoded in ISO-8892 or some other standard. I suppose it would be fine to remove the deprecated function.

**Comment by tassoman** [comment]
Looks like this can be closed, because merged and #19343 can be reviewed. Now PHP 8.2 is actual stable version (since a week)

**Comment by tassoman** [comment]
Hello there, can you confirm it was released in v3.0.16 ?
Thanks!

**Comment by szymach** [comment]
Hello, 
See [here](https://github.com/szymach/c-pchart/commit/7cbaf0d9ec4622d3699c476c24c2ffb99816c8e3).
